# Generated by Django 3.1.3 on 2020-11-27 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('latitude', models.FloatField()),
                ('longtitude', models.FloatField()),
                ('representative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(max_length=11)),
                ('telephone_number', models.CharField(max_length=10)),
                ('facebook_link', models.CharField(max_length=127)),
                ('office_hours', models.CharField(max_length=20)),
                ('weekly_views', models.IntegerField()),
                ('total_views', models.IntegerField()),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bank', 'Bank'), ('Electronics', 'Electronics'), ('Fast Food Chain', 'Fast Food Chain'), ('Gas Station', 'Gas Station'), ('Grocery', 'Grocery'), ('Hardware and Construction Materials', 'Hardware and Construction Materials'), ('Hospital', 'Hospital'), ('Payment Gateway', 'Payment Gateway'), ('Pharmacy', 'Pharmacy'), ('Restaurants', 'Restaurants'), ('Supermarket', 'Supermarket'), ('Utility Company', 'Utility Company')], max_length=127, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessToService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='linked_services', to='mainapp.business')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_name', to='mainapp.service')),
            ],
        ),
        migrations.AddField(
            model_name='business',
            name='services',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business', to='mainapp.service'),
        ),
    ]
