# Generated by Django 3.1.3 on 2020-11-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='office_hours',
        ),
        migrations.AddField(
            model_name='business',
            name='office_hours_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='business',
            name='office_hours_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=127, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='telephone_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='total_views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='business',
            name='weekly_views',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
